### ISSUE TITLE
SHC AI Contest Announcement By Krarilotus

### ISSUE THREAD

**Issue by Lolasik011** [Sh0wdown/UnofficialCrusaderPatch#413]
1 SHC AI Contest Announcement By @Krarilotus .
https://www.youtube.com/watch?v=xs-rOotzJFQ

2  Stronghold Crusader 4Char castle mod https://www.youtube.com/watch?v=ZqM81sr4HwA
3  Stronghold Crusader KI Design Schnelleinstieg (ft. Igel KI) https://www.youtube.com/watch?v=5O5RXLWwrCc
4 AI Contest Summary July19  https://www.youtube.com/watch?v=oIdxYXPmHVc&feature=youtu.be

EDIT AI Design Contest 08-10/2019 Announcement https://www.youtube.com/watch?v=SOOG1bKbVKM

**Comment by Krarilotus** [comment]
oh lol, thats no issue with the UCP btw.
But thx for mentioning it. I hope to get more values figured out :)

**Comment by GRhin** [comment]
maybe, but for us English only players this is pretty much the only place you can reach us.

**Comment by Krarilotus** [comment]
https://www.youtube.com/watch?v=8WgSMmWNzvQ
Just fyi, if you want some basics to beat the challenge from the contest, you might find them here.
I hope i can help you out with this. Its far from perfect, maybe i have to redo it, for making it worth beeing an official tutorial, but lets first find out the missing values!

**Comment by Mizo5119** [comment]
I saw the video. Very informative. I was wondering if we can have a Google doc that list all the missing values and what they are for similar to the notepad you were using.

**Comment by Krarilotus** [comment]
Good idea, i will make a sheet tomorrow that everyone can fill with suggestions for values, and one that lists comfirmed values, and who confirmed them.

**Comment by Krarilotus** [comment]
> I saw the video. Very informative. I was wondering if we can have a Google doc that list all the missing values and what they are for similar to the notepad you were using.
Here is the sheet for discussion:
https://docs.google.com/document/d/1hlxXA5rfIfGwm0oU_faScNCZArDJIk8lqbbWQ4gVdMc/edit?usp=drivesdk

Here are all the values so far put together:
https://docs.google.com/document/d/1idW3fsOcRgBf2ZzM-q4zD6jtjbH9yLBlAhT31d7KYbo/edit?usp=drivesdk

**Comment by Lolasik011** [comment]
> > I saw the video. Very informative. I was wondering if we can have a Google doc that list all the missing values and what they are for similar to the notepad you were using.
> 
> Here is the sheet for discussion:
> https://docs.google.com/document/d/1hlxXA5rfIfGwm0oU_faScNCZArDJIk8lqbbWQ4gVdMc/edit?usp=drivesdk
> 
> Here are all the values so far put together:
> https://docs.google.com/document/d/1idW3fsOcRgBf2ZzM-q4zD6jtjbH9yLBlAhT31d7KYbo/edit?usp=drivesdk

0_0 Wow !!! You GOD!!! 

It is necessary that byburton add new variables, and update AIC ...

**Comment by Krarilotus** [comment]
> It is necessary that @ByBurton add new variables, and update AIC ...
Actually, @ByBurton didnt want to get mentioned with the new values, but most of them i got hinted by her, so i guess she is already very busy doing exactly that :)
There should be a prototype of 2.13 somewhere. For now i guess we can still use 2.12, since it offers all the values modable already, just doesnt name them yet.

**Comment by Russianstory** [comment]
А об чём речь тут?) я не понимаю вообще)  Изменения набора солдат каждому из Ботов?

**Comment by Krarilotus** [comment]
мы говорим о том, что они набирают, как быстро они набирают, и как они используют свою эко и свою армию в целом.
Вы можете настроить некоторые характеристики, изменив файл .aic, предоставленный патчем для сообщества.
но некоторые значения до сих пор неизвестны, если вы понимаете по-английски, вы можете посмотреть данные видео сверху, чтобы узнать больше

we are talking about what they recruit, how fast they recruit, and how they use their eco and their army in general. Some of these characteristics, you can adjust by modifying the .aic file from the community patch, but some are still unknown. In the videos linked above, some of this is explained

**Comment by ByBurton** [comment]
I added them, but they require a lot more testing. @Krarilotus 
Most values do kinda what you said, but especially the variable you said determines the siege army rallies at seems veeery questionable. 
What I could confirm kind of:
-Unknown131 if set to 0 army does not rally at an enemy fallen lord's gravestone anymore (determines rally after victory)
-Unknown129 the enemy retreats back after victory, but attacks as soon as the percentage that this value represents of the remaining forces compared to the original count of units is met
-Unknown130 I could not verify or test yet
-Unknown127 as mentioned above can not say if the ai really rallies somewhere else.

**Comment by Krarilotus** [comment]
> I added them, but they require a lot more testing. @Krarilotus
> Most values do kinda what you said, but especially the variable you said determines the siege army rallies at seems veeery questionable.
> What I could confirm kind of:
> -Unknown131 if set to 0 army does not rally at an enemy fallen lord's gravestone anymore (determines rally after victory)
> -Unknown129 the enemy retreats back after victory, but attacks as soon as the percentage that this value represents of the remaining forces compared to the original count of units is met
> -Unknown130 I could not verify or test yet
> -Unknown127 as mentioned above can not say if the ai really rallies somewhere else.

Unknown127 might only interfere with the rally point, but coud be something completely different. Unknown130 is kind of hard to test, since siegengines are already bugged and getting good testingconditions is hard. I tested this while i made an AI to proof how the AI Contest challenge coud be beaten, and especially when set to 100, the behaviour is clearly seen as waiting for all siege units to die before mainattack units start moving.

And for 129, it might be the percentage for all attackingforce groups. But i am not sure. With the settings in my aic video, the ai shoud have attacked immediatly again after killing of one of the wolfs in the match rat vs 7 wolfs, but it didnt. I can only imagine it was due to the fact, that all its assassins died in the encounter. Maybe some other factors count aswell, for example if its defense is low, if it fears an incoming attack, if it is the strongest ruler etc.

Because these variables are hard to pin down, they are not made official. And i woud highly appriciate more ideas for testing these and more people trying to confirm them, before announcing them officially.

**Comment by Lolasik011** [comment]
@ByBurton and @Krarilotus You are great fellows. Without you there would be no future for Stronghold Unofficial patch and AIC ... Thank you so much !!!

**Comment by Krarilotus** [comment]
> @ByBurton and @Krarilotus You are great fellows. Without you there would be no future for Stronghold Unofficial patch and AIC ... Thank you so much !!!

I think most credit should go to sh0wdown. I am just a random guy using the patcher as we all do

**Comment by Lolasik011** [comment]
> I think most credit should go to sh0wdown. I am just a random guy using the patcher as we all do
@Sh0wdown 
I am very grateful to him for what he has done a miracle!

**Comment by Russianstory** [comment]
Лоласик я ваще не врубился)  я к тому, что  - проблема вроде вижу мод делается и делается большая обновка для игры и это здорово! Но оно по-моему как -то разбросано по форуму что я не могу собрать всю информацию полностью воедино об этом моде) Вижу и новый ИИ и некоторые исправления и ещё что и  крепости новые - а получается как то разбросано)) Может, где-то всё складывается в одном месте?). А так конечно да и от меня большая благодарность всем тем, кто делает именно первую часть лучше.

=

Lolasik, I finally did not get it) I mean that - a problem like I see the mod is being done and a large upgrade is being made for the game and this is great! But in my opinion it is somehow scattered around the forum that I can not collect all the information completely together about this fashion) I see a new AI and some corrections and more that new fortresses - but it turns out like that is scattered)) Maybe somewhere everything is in one place?). And of course, yes, and from me a big thanks to all those who are doing exactly the first part better.

**Comment by GRhin** [comment]
Russian story, correct me if I have misunderstood, but basically the latch has an added feature using byburton's aic editor which allows you to modify AI behaviour. As well as this firefly long ago released an SUV editor which allows you to design AI castles. 
These are designed to be available for general users to design  their own AI players, the result is not part of the patch. 
 The video krarilotus posted focuses mainly on the aic editing side as it isn't very user friendly and still not fully understood even by the creator.
Ultimately the idea is that this allows the average user to create and upload their own AIs for other players to enjoy. You can already download castles on heavengames.

**Comment by Russianstory** [comment]
@GRhin 
I figured it out. I thought that a great update for stronghold would include both fortresses and AI and fix bugs and glitches in the game and add new ideas and change the balance and parameters. I thought that the modification would be comprehensive and most complete. =) If so, I will be happy to install this large and useful option over the game in one action. =) I always hold the position of merging and creating a large project - fashion or patch ... Although I myself am stupid .... with sounds from my fashion ...
Я это понял Я думал что большое обновление для стронгхолда будет включать и крепости и ИИ  и исправление багов и глюков в игре и добавление новых идей и изменения баланса и параметров. Я думал что Модификация будет всеобъемлющая и наиболее полная. =) Если будет так то буду рад одним действием установить поверх игры этот большой и полезный вариант. =) Я всегда придерживаюсь позиции объединения слияния и создания большого проекта - мода или патча... Хотя сам бестолковый....с меня звуки с моего мода...

**Comment by Krarilotus** [comment]
The patcher already includes custom castles, evrey's and tatha's as i believe, and overall ai fixes. But the main point as @GRhin said is the modability for a broader audience.
It is difficult to define the 'best' set of castles, as everyone and their dog has made castles, and they differ in many aspects from efficiency, to character and style over historical corectness up to complete different ai designs.

**Comment by GRhin** [comment]
> I thought that a great update for stronghold would include both fortresses and AI and fix bugs and glitches in the game and add new ideas and change the balance and parameters. I thought that the modification would be comprehensive and most complete. =) If so, I will be happy to install this large and useful option over the game in one action. =) I always hold the position of merging and creating a large project - fashion or patch ... Although I myself am stupid .... with sounds from my fashion 

This patch does do everything you mentioned. There are fixed and updated castles from Pitchneeded, evrey and tatha, and there is a "Vanilla-bugfix.aic" in the installer.
I see what you want in having all things in one place, and with the current relatively small modding community it may be practical, however if these features bring more modders into the community, having everyones work available would result in a lot of options in the patch, and alot of unnecessary updates to include them. Krarilotus has made several AIs that I know of, and there are 4 or 5 members of the community that I think are using these features. If they all made even 2 or 3 AIs each, the mod would become cumbersome and put alot of people off using it, alot more than making people to upload their own projects somewhere else and import into the patch as they desire (just create an aic folder, then copy the aic and aiv files into the appropriate directories). Maybe a good midground would be to create some software that compiles AI projects into an install file to make installing them simpler?

**Comment by GRhin** [comment]
FYI, competition results - https://youtu.be/oIdxYXPmHVc

**Comment by Krarilotus** [comment]
this has been complete, you can make a new issue when the 3rd contest is out. 2nd Contest has been won by Starshine, comclusion video is still missing cuz not enough time... but comingsoon!
